/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "asoc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Estado *
ponerasociacion_1(int arg1, char *arg2, char *arg3,  CLIENT *clnt)
{
	ponerasociacion_1_argument arg;
	static Estado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	if (clnt_call (clnt, PONERASOCIACION, (xdrproc_t) xdr_ponerasociacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_Estado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ResultadoBusqueda *
obtenerasociacion_1(int arg1, char *arg2,  CLIENT *clnt)
{
	obtenerasociacion_1_argument arg;
	static ResultadoBusqueda clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, OBTENERASOCIACION, (xdrproc_t) xdr_obtenerasociacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ResultadoBusqueda, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Estado *
borrarasociacion_1(int arg1, char *arg2,  CLIENT *clnt)
{
	borrarasociacion_1_argument arg;
	static Estado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, BORRARASOCIACION, (xdrproc_t) xdr_borrarasociacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_Estado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ResultadoEnumerar *
enumerar_1(int arg1,  CLIENT *clnt)
{
	static ResultadoEnumerar clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ENUMERAR,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_ResultadoEnumerar, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
