/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "asoc.h"

bool_t
xdr_NodoDiccionarioPTR (XDR *xdrs, NodoDiccionarioPTR *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (NodoDiccionario), (xdrproc_t) xdr_NodoDiccionario))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NodoDiccionario (XDR *xdrs, NodoDiccionario *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->clave, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->valor, ~0))
		 return FALSE;
	 if (!xdr_NodoDiccionarioPTR (xdrs, &objp->sig))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Estado (XDR *xdrs, Estado *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ResultadoBusqueda (XDR *xdrs, ResultadoBusqueda *objp)
{
	register int32_t *buf;

	 if (!xdr_Estado (xdrs, &objp->s))
		 return FALSE;
	switch (objp->s) {
	case OK:
		 if (!xdr_string (xdrs, &objp->ResultadoBusqueda_u.valor, ~0))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_ResultadoEnumerar (XDR *xdrs, ResultadoEnumerar *objp)
{
	register int32_t *buf;

	 if (!xdr_Estado (xdrs, &objp->s))
		 return FALSE;
	switch (objp->s) {
	case OK:
		 if (!xdr_NodoDiccionarioPTR (xdrs, &objp->ResultadoEnumerar_u.diccionario))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_ponerasociacion_1_argument (XDR *xdrs, ponerasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_obtenerasociacion_1_argument (XDR *xdrs, obtenerasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_borrarasociacion_1_argument (XDR *xdrs, borrarasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	return TRUE;
}
