/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "asoc.h"
#include <stdlib.h>

#define MAX_STRING 50

int haFallado = 0;

CLIENT* crearCliente(char * host){
	CLIENT* clnt = NULL;
#ifndef	DEBUG
	clnt = clnt_create (host, ASOCIACIONPROG, ASOCIACIONVERS, "udp");
	if (clnt == NULL) {
		haFallado = 1;
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	return clnt;
}

void destruirCliente(CLIENT* clnt){
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int leerID(){
	char strID[11];
	printf("Introduce la ID del diccionario: ");
	scanf("%s",strID);
	return atoi(strID);
}

void leerClave(char * cad){
	printf("Introduce la clave: ");
	scanf("%s",cad);
}

void leerValor(char * cad){
	printf("Introduce el valor asociado a la clave: ");
	scanf("%s",cad);
}

/*
 * Funciones que van a llamar al servidor.
 */

void asociarValor(CLIENT * clnt){
	
	int id = leerID();
	char clave[MAX_STRING], valor[MAX_STRING];
	leerClave(clave);
	leerValor(valor);
	
	Estado * res = ponerasociacion_1(id, clave, valor, clnt);
	if (res == (Estado *) NULL) {
		haFallado = 1;
		clnt_perror (clnt, "call failed");
	}else{
		if(*res == OK){
			printf("\nLa clave ha sido asociada a su valor.\n");
		}else if(*res == Sustituido){
			printf("\nLa clave ya existia en ese diccionario, se ha actualizado su valor a: %s\n", valor);
		}else if(*res == FalloMemoria){
			printf("\nERROR: No se ha podido añadir la clave.\n");
		}
	}
}

void consultarValor(CLIENT * clnt){
	
	int id = leerID();
	char clave[MAX_STRING];
	leerClave(clave);
	
	ResultadoBusqueda  * res;

	res = obtenerasociacion_1(id, clave, clnt);
	if (res == (ResultadoBusqueda *) NULL) {
		haFallado = 1;
		clnt_perror (clnt, "call failed");
	}else{
		if(res->s == OK){
			printf("\nLa clave \"%s\" en el diccionario %d tiene asociada el valor \"%s\".\n", clave, id, res->ResultadoBusqueda_u.valor);
		}else if(res->s == NoEncontrado){
			printf("\nLa clave \"%s\" no se ha encontrado en el diccionario %d.\n", clave, id);
		}
	}
}

void borrarAsociacion(CLIENT * clnt){
	
	int id = leerID();
	char clave[MAX_STRING];
	leerClave(clave);
	
	Estado  * res;

	res = borrarasociacion_1(id, clave, clnt);
	if (res == (Estado *) NULL) {
		haFallado = 1;
		clnt_perror (clnt, "call failed");
	}else{
		if(*res == OK){
			printf("\nLa asociacion de la clave \"%s\" del diccionario %d se ha eliminado.\n", clave, id);
		}else if(*res == NoEncontrado){
			printf("\nLa clave \"%s\" no se ha encontrado en el diccionario %d.\n", clave, id);
		}
	}
}

void mostrarAsociaciones(CLIENT * clnt){
	
	int id = leerID();
	
	ResultadoEnumerar * res = enumerar_1(id, clnt);
	if (res == (ResultadoEnumerar *) NULL) {
		haFallado = 1;
		clnt_perror (clnt, "call failed");
	}else if(res->s == NoEncontrado){
		printf("\nNo se encuentra un diccionario identificado con la id %d.\n", id);
	}else if(res->s == OK){
		printf("\nEl diccionario %d contiene los siguientes pares \"clave -> valor\":\n", id);
		NodoDiccionario* it = res->ResultadoEnumerar_u.diccionario;
		while(it!=NULL){
			printf("%s -> %s\n", it->clave, it->valor);
			it = it->sig;
		}
	}
}

int
main (int argc, char *argv[])
{
	char *host;
	int opcion;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	CLIENT * clnt = crearCliente(host);
	
	while(!haFallado){
		printf("\nIntroduce una de las opciones: \n");
		printf("1.- Asociar un valor.\n");
		printf("2.- Consultar un valor.\n");
		printf("3.- Borrar una asociación.\n");
		printf("4.- Mostrar asociaciones.\n");
		printf("5.- Salir.\n");

		scanf("%d", &opcion);
		while (opcion < 1 || opcion > 5){
			printf ("Opción no válida. Vuelva a introducir una opción.\n");
			scanf("%d", &opcion);
		}

		if(opcion == 1){
			asociarValor(clnt);
		}else if(opcion == 2){
			consultarValor(clnt);
		}else if(opcion == 3){
			borrarAsociacion(clnt);
		}else if(opcion == 4){
			mostrarAsociaciones(clnt);
		}else{
			destruirCliente(clnt);
			exit(0);
		}
	}
	destruirCliente(clnt);
}
