/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASOC_H_RPCGEN
#define _ASOC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct NodoDiccionario NodoDiccionario;

typedef NodoDiccionario* NodoDiccionarioPTR;

struct NodoDiccionario {
	char *clave;
	char *valor;
	NodoDiccionarioPTR sig;
};

enum Estado {
	OK = 0,
	Sustituido = 1,
	NoEncontrado = 2,
	FalloMemoria = 3,
};
typedef enum Estado Estado;

struct ResultadoBusqueda {
	Estado s;
	union {
		char *valor;
	} ResultadoBusqueda_u;
};
typedef struct ResultadoBusqueda ResultadoBusqueda;

struct ResultadoEnumerar {
	Estado s;
	union {
		NodoDiccionarioPTR diccionario;
	} ResultadoEnumerar_u;
};
typedef struct ResultadoEnumerar ResultadoEnumerar;

struct ponerasociacion_1_argument {
	int arg1;
	char *arg2;
	char *arg3;
};
typedef struct ponerasociacion_1_argument ponerasociacion_1_argument;

struct obtenerasociacion_1_argument {
	int arg1;
	char *arg2;
};
typedef struct obtenerasociacion_1_argument obtenerasociacion_1_argument;

struct borrarasociacion_1_argument {
	int arg1;
	char *arg2;
};
typedef struct borrarasociacion_1_argument borrarasociacion_1_argument;

#define ASOCIACIONPROG 0x20000001
#define ASOCIACIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PONERASOCIACION 1
extern  Estado * ponerasociacion_1(int , char *, char *, CLIENT *);
extern  Estado * ponerasociacion_1_svc(int , char *, char *, struct svc_req *);
#define OBTENERASOCIACION 2
extern  ResultadoBusqueda * obtenerasociacion_1(int , char *, CLIENT *);
extern  ResultadoBusqueda * obtenerasociacion_1_svc(int , char *, struct svc_req *);
#define BORRARASOCIACION 3
extern  Estado * borrarasociacion_1(int , char *, CLIENT *);
extern  Estado * borrarasociacion_1_svc(int , char *, struct svc_req *);
#define ENUMERAR 4
extern  ResultadoEnumerar * enumerar_1(int , CLIENT *);
extern  ResultadoEnumerar * enumerar_1_svc(int , struct svc_req *);
extern int asociacionprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PONERASOCIACION 1
extern  Estado * ponerasociacion_1();
extern  Estado * ponerasociacion_1_svc();
#define OBTENERASOCIACION 2
extern  ResultadoBusqueda * obtenerasociacion_1();
extern  ResultadoBusqueda * obtenerasociacion_1_svc();
#define BORRARASOCIACION 3
extern  Estado * borrarasociacion_1();
extern  Estado * borrarasociacion_1_svc();
#define ENUMERAR 4
extern  ResultadoEnumerar * enumerar_1();
extern  ResultadoEnumerar * enumerar_1_svc();
extern int asociacionprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_NodoDiccionarioPTR (XDR *, NodoDiccionarioPTR*);
extern  bool_t xdr_NodoDiccionario (XDR *, NodoDiccionario*);
extern  bool_t xdr_Estado (XDR *, Estado*);
extern  bool_t xdr_ResultadoBusqueda (XDR *, ResultadoBusqueda*);
extern  bool_t xdr_ResultadoEnumerar (XDR *, ResultadoEnumerar*);
extern  bool_t xdr_ponerasociacion_1_argument (XDR *, ponerasociacion_1_argument*);
extern  bool_t xdr_obtenerasociacion_1_argument (XDR *, obtenerasociacion_1_argument*);
extern  bool_t xdr_borrarasociacion_1_argument (XDR *, borrarasociacion_1_argument*);

#else /* K&R C */
extern bool_t xdr_NodoDiccionarioPTR ();
extern bool_t xdr_NodoDiccionario ();
extern bool_t xdr_Estado ();
extern bool_t xdr_ResultadoBusqueda ();
extern bool_t xdr_ResultadoEnumerar ();
extern bool_t xdr_ponerasociacion_1_argument ();
extern bool_t xdr_obtenerasociacion_1_argument ();
extern bool_t xdr_borrarasociacion_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASOC_H_RPCGEN */
